global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'default'
    file_sd_configs:
    - files:
      - '/etc/prometheus-config/prometheus-targets.yml'
    metric_relabel_configs:
    - action:        labelmap
      regex:         'io_rancher_(container_name|stack_service_name|container_system)$'
      replacement:   '$1'
