global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
rule_files:
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: puppetdb
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/prometheus-puppetdb/targets.yml
    refresh_interval: 5m
  relabel_configs:
  - source_labels: [metrics_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [scheme]
    separator: ;
    regex: (.+)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [certname]
    separator: ;
    regex: (.+?)\.(.+)
    target_label: instance
    replacement: ${1}
    action: replace
  - separator: ;
    regex: ^metrics_path$|^scheme$
    replacement: $1
    action: labeldrop
