# Default values for prometheus-puppetdb-sd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: camptocamp/prometheus-puppetdb-sd
  tag: 0.11.2
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheusPuppetdbSd:
  args:
    output.method: k8s-secret
    output.k8s-secret.secret-name: prometheus-puppetdb-sd-output
    output.k8s-secret.secret-key: puppetdb-sd.yml
  Extraconfigmapmounts: []
  extraSecretMounts: []


prometheus:
  initChownData:
    enabled: false

  alertmanager:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  pushgateway:
    enabled: false

  server:
    extraSecretMounts:
      - name: prometheus-puppetdb-sd-out
        secretName: prometheus-puppetdb-sd-out
        mountPath: /etc/prometheus/puppetdb.yml
        subPath: puppetdb.yml
        readOnly: true

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
              - localhost:9090
        - job_name: puppetdb
          file_sd_configs:
            - files:
              - /etc/prometheus/puppetdb.yml
          relabel_configs:
            - source_labels: [metrics_path]
              regex: (.+)
              action: replace
              target_label: __metrics_path__
            - source_labels: [scheme]
              regex: (.+)
              action: replace
              target_label: __scheme__
            - source_labels: [certname]
              regex: (.+?)\.(.+)
              action: replace
              target_label: instance
              replacement: ${1}
            - regex: ^metrics_path$|^scheme$
              action: labeldrop
